fix: Sync missing entries when running with multiple clients and add …
atsign-foundation/at_client_sdk pull request #1024
Opened 2023-05-10 05:07 UTC by sitaram-kalluri

**- What I did**
* When multiple clients pump data to the server and attempt to sync the changes, conflicts arise resulting in missing and inconsistencies between clients. Due to conflicts, Client-1 may be missing the commit-Id synced from Client-2 and vice-versa. This occurs because the commit-Id in client-1 is greater than the commit-Id synced from client-2.
* Please refer to the following [google docs](https://docs.google.com/spreadsheets/d/1JLwe0OupRJSkPC52r9Bo3kshcWF5FRHvLdgHuqj1Jyg/edit?usp=share_link) for more details on the issue.

**- How I did it**
* On the client side, currently, we are updating the "lastReceivedServerCommitId" when pushing and pulling the server commit entries. To fix the issue, update the "lastReceivedServerCommitId" only when the client pulls the changes. Because "lastReceivedServerCommitId" is not updated on pushing the changes, we get synced entries back to the client; but if the same exists in the un-committed entries list the data will be overwritten. To address this issue, on pulling the changes, if an entry with the same key exists in uncommitted entries, skip committing that particular entry to local.
* With new changes, lastReceivedServerCommitId will not be updated when pulling the changes. Hence removed unit tests that assert the same.

**- How to verify it**
* All the existing functional and end2end tests should pass.
* Introduced a new test in End2End tests which initialized two clients(in isolates) and pump data to the server concurrently. In the end, fetch the commit logs of both the clients and the server and compare the commit-Id. This test needs changes in the server to fetch the latest CommitEntry of each key. The changes are available in the following PR: https://github.com/atsign-foundation/at_server/pull/1344. 
* Above test is open for review - tests/at_end2end_test/test/sync_multiple_client_test.dart. Since the changes in at_server are not yet merged, added a skip tag to avoid test failure.

**- Description for the changelog**
* Fix: Missing sync entries when multiple clients pump data concurrently.

2023-05-10 09:33 UTC, murali-shris requested changes

2023-05-10 09:33 UTC, murali-shris commented on packages/at_client/lib/src/service/sync_service_impl.dart
>          List<dynamic> listOfCommitEntriesToSync =
you can rename listOfCommitEntriesToSync to listOfCommitEntriesFromServer

2023-05-10 10:16 UTC, sitaram-kalluri commented on packages/at_client/lib/src/service/sync_service_impl.dart
>          List<dynamic> listOfCommitEntriesToSync =
Sure Murali

2023-05-14 18:55 UTC, gkc commented
This PR is still marked as Draft, is it ready for review?

2023-05-15 05:41 UTC, sitaram-kalluri commented
> This PR is still marked as Draft, is it ready for review?

@gkc: Yes, the PR is ready for review. 

The sync isolate test has pending work. At the moment, the test has only 5 keys to inject. The keys are limited to 5 (for now) to ensure the test runs in GitHub action successfully and then incrementally, scale up the keys to 50.

2023-05-15 11:25 UTC, gkc requested changes
In the PR description you mention
> Since the changes in at_server are not yet merged, added a skip tag to avoid test failure.

Instead of a `skip` tag, please instead check the atServer version and require version >= 3.0.32

2023-05-15 11:27 UTC, sitaram-kalluri commented
> In the PR description you mention
> 
> > Since the changes in at_server are not yet merged, added a skip tag to avoid test failure.
> 
> Instead of a `skip` tag, please instead check the atServer version and require version >= 3.0.32

Sure, Gary.

2023-05-29 10:46 UTC, sitaram-kalluri commented
@gkc: The end-2-end tests are failing due to time-out exception. When i run the test in local, i do not see the timeout exception. My guess is because there are not lot of commit-id's to sync, test is taking more than usual time to sync. I will debug and find way to fix the timeout exception. Meanwhile, can we remove the "tests/at_end2end_test/test/sync_multiple_client_test.dart" from the PR and push the other changes? Once the test is stable, will add it to the e2e test suite.

2023-05-29 10:48 UTC, gkc commented
SGTM

2023-06-01 12:27 UTC, gkc commented
> > In the PR description you mention
> > > Since the changes in at_server are not yet merged, added a skip tag to avoid test failure.
> > 
> > 
> > Instead of a `skip` tag, please instead check the atServer version and require version >= 3.0.32
> 
> Sure, Gary.

I don't see this in the PR ... ?

2023-06-01 12:27 UTC, gkc requested changes

2023-06-01 12:27 UTC, gkc commented on packages/at_client/lib/src/service/sync_service_impl.dart
> +      //keyInfo.conflictInfo = conflictInfo;
Why is the above code commented out?

2023-06-01 12:27 UTC, gkc commented on packages/at_client/lib/src/service/sync_service_impl.dart
>                await decryptionManager.decrypt(atKey, serverEncryptedValue);
What should happen if decryption happens to fail?

2023-06-01 12:27 UTC, gkc commented on packages/at_client/test/sync_new_test.dart
> -
Why were the above tests removed?

2023-06-01 15:10 UTC, sitaram-kalluri commented on packages/at_client/test/sync_new_test.dart
> -
Earlier, the "lastReceivedServerCommitId" is updated when sync entries are pushed to server and pulled from server. With the new approach we do not update the lastReceivedServerCommitId when we sync the uncommitted entries to server. Hence removed the code that updates the "lastReceivedServerCommitId" when we push the changes to server. Hence removed the related unit tests also.

2023-06-02 04:37 UTC, sitaram-kalluri commented
> > > In the PR description you mention
> > > > Since the changes in at_server are not yet merged, added a skip tag to avoid test failure.
> > > 
> > > 
> > > Instead of a `skip` tag, please instead check the atServer version and require version >= 3.0.32
> > 
> > 
> > Sure, Gary.
> 
> I don't see this in the PR ... ?

Referring to the above discussion, The test is removed from the PR since the test often fails due to TimeOut Exception. Will raise a separate PR once the test is stable.

2023-06-02 05:42 UTC, gkc approved these changes, later dismissed

2023-06-02 10:34 UTC, sitaram-kalluri commented
@gkc: Have updated the PR with the following changes:
* Extend the existing unit test to assert on setting the values into ConflictInfo for a shared key.
* Added a new unit test to assert when exception occurs when decrypting the value in "setConflictInfo" method.

2023-06-02 12:23 UTC, gkc approved these changes

2023-06-05 04:39 UTC, murali-shris approved these changes

2023-06-05 05:17 UTC, merged