fix: added a check to handle self symmetric shared
atsign-foundation/at_client_sdk pull request #1072
Opened 2023-06-20 23:15 UTC by Xlin123

**- What I did**
just testing rn
**- How I did it**

**- How to verify it**

**- Description for the changelog**

2023-06-21 00:03 UTC, Xlin123 commented
conclusion: to fix the issue I need to use at_chops to do RSA encryption because it's trying to use the private symmetric key to decrypt an AES key. If there's any place where at_chops is used so I can see an example it would be very helpful.

2023-06-21 01:30 UTC, gkc commented
See here to understand what happens when, as `@bob`, you decrypt a message from `@alice` https://github.com/atsign-foundation/at_protocol/blob/trunk/usage-examples/how-to-exchange-encrypted-data.md#4-fetch-the-symmetric-key-which-alice-shared

The code which handles this is in shared_key_decryption.dart, and part of that code handles the fetching of the symmetric key, decoding from base64, and decrypting using at_chops and the 'receiving' atSign's  private key

2023-06-21 12:27 UTC, Xlin123 commented
Ahhh, okay got it. I did some work on self_key_decryption first since keys like "shared_key.bob@alice" I think fall under self keys. Let me know if that's incorrect and I can just revert changes. I'll do shared_key_decryption when I get home.

2023-06-28 13:36 UTC, gkc requested changes

2023-06-28 13:36 UTC, gkc commented on packages/at_client/lib/src/decryption_service/self_key_decryption.dart
> +    if (atKey.key == "shared_key") {
The copy alice will create for themselves of a shared key they cut for bob will be `shared_key.bob@alice`. Will this test work? What happens when you use this branch with your REPL?

2023-06-28 13:36 UTC, gkc commented on packages/at_client/lib/src/decryption_service/self_key_decryption.dart
> +      if (atKey.sharedWith != _atClient.getCurrentAtSign()) {
sharedWith is not set - when we create `shared_key.bob@alice`  - again, what happens when you run this branch with your REPL? Do you get the desired outcomes?

2023-06-28 19:49 UTC, Xlin123 commented
Two decryptable cases
![image](https://github.com/atsign-foundation/at_client_sdk/assets/42496953/f7caaba7-74f4-4d47-b7e3-01f331798f84)

However, ` /get @bob:shared_key@alice ` isn't throwing it's exception properly. I should finish it tonight.

2023-06-28 21:14 UTC, Xlin123 commented
![image](https://github.com/atsign-foundation/at_client_sdk/assets/42496953/501ebee5-8bf1-4383-acb7-644e4d0effce)
@gkc   I think I fixed everything.

2023-06-28 23:30 UTC, gkc commented
Please add unit tests which verify each case

2025-07-08 16:54 UTC, closed without merging