fix: at_commons 4.0.0 uptake in at_Client
atsign-foundation/at_client_sdk pull request #1192
Opened 2024-01-04 05:58 UTC by purnimavenkatasubbu

**- What I did**
  Updated the following dependencies

-    at_commons to v4.0.0
-    at_utils to v3.0.16
-    at_lookup to v3.0.44
-    at_chops to v1.0.7
-    at_persistence_secondary_server to v3.0.60

Also made updates as per the at_commons:4.0.0 changes
**- How I did it**

**- How to verify it**
All the unit, functional, and end2end tests should pass
All the apps should work fine
**- Description for the changelog**

2024-01-08 12:32 UTC, gkc reviewed
This PR has a **lot** of files changed

Via the "Files Changed" tab), please add a brief explanation of the reason for each change (at least the first time it appears - e.g. the change from `atKey.key ?? ''` to `atKey.key` appears in many place - please explain why.)

Please also consider for every change here whether it is a breaking change for the at_client package

2024-01-09 06:32 UTC, sitaram-kalluri commented on packages/at_client/lib/src/at_collection/impl/collection_methods_impl.dart
> +        key: atKey.key,
Earlier, the AtKey.key is a nullable variable, but the named argument "key" does not accept NULL value. Hence defaulted to empty string in case of null. In at_commons-4.0.0, the AtKey.key is prefixed with late and "?" (which denotes that variable can be null) is removed because key can never be null in AtKey,

2024-01-09 06:39 UTC, sitaram-kalluri commented on packages/at_client/lib/src/at_collection/impl/default_key_maker.dart
> +      ..metadata.ccd = objectLifeCycleOptions?.cascadeDelete ?? true
In at_commons-> AtKey, updated the "metadata" field from nullable field (removed "?"). With the change, the field is defaulted to Metadata instance - "Metadata metadata = Metadata();"

2024-01-09 07:16 UTC, sitaram-kalluri commented on packages/at_client/lib/src/client/at_client_impl.dart
> +    var builder = DeleteVerbBuilder()..atKey = atKey;
The fields of AtKey are now substituted with AtKey instances in all verb builders. The atKey object is directly assigned, and the code responsible for assigning fields of atKey has been removed

2024-01-09 07:17 UTC, sitaram-kalluri commented on packages/at_client/lib/src/client/at_client_impl.dart
> +    if (upperCaseRegex.hasMatch(atKey.key) ||
Since Atkey.key is modified as a non null variable in at_commons, removed the non-null assertion operator

2024-01-09 07:18 UTC, sitaram-kalluri commented on packages/at_client/lib/src/client/at_client_impl.dart
> +    if (atKey.metadata.namespaceAware) {
Since Atkey.metadata is modified as a non null variable (defaulted to "Metadata()"), removed the non-null assertion operator

2024-01-09 07:19 UTC, sitaram-kalluri commented on packages/at_client/lib/src/client/at_client_impl.dart
> +      ..atKey = atKey
The fields of AtKey are now substituted with AtKey instances in all verb builders. The atKey object is directly assigned, and the code responsible for assigning fields of atKey has been removed

2024-01-09 07:20 UTC, sitaram-kalluri commented on packages/at_client/lib/src/client/at_client_impl.dart
> +        .executeVerb(builder, sync: SyncUtil.shouldSync(updateKey));
Since Atkey.key is modified as a non null variable in at_commons, removed the non-null assertion operator

2024-01-09 07:22 UTC, sitaram-kalluri commented on packages/at_client/lib/src/client/at_client_impl.dart
> +      String? notifier = AtConstants.system,
Replaced the use of legacy at_constants (which are now removed from at_commons -4.0.0) with new references to new AtConstants file

2024-01-09 07:25 UTC, sitaram-kalluri commented on packages/at_client/lib/src/client/verb_builder_manager.dart
> +        (atKey.metadata.isPublic && !atKey.metadata.isCached)) {
Since AtKey.metadata is not null and boolean fields in Metadata have default values instead of null, removed the null check and non null assertion operator

2024-01-09 07:31 UTC, sitaram-kalluri commented on packages/at_client/lib/src/manager/sync_manager.dart
> +      if (metaData[AtConstants.ttl] != null)
The AT_TTL, AT_TTB, AT_TTR...which is are a part of "at_constants_legacy.dart" which is deprecated and removed in at_commons-4.0.0. The "at_constants_legacy.dart" is replaced with "at_constants.dart" in at_commons.

2024-01-09 07:33 UTC, sitaram-kalluri commented on packages/at_client/lib/src/transformer/request_transformer/get_request_transformer.dart
> -    atKey.metadata ??= Metadata();
Since AtKey.metadata is defaulted to "Metadata()". Hence removed the above line.

2024-01-09 07:33 UTC, sitaram-kalluri commented on packages/at_client/lib/src/transformer/request_transformer/notify_request_transformer.dart
> -    notificationParams.atKey.metadata ??= Metadata();
Since AtKey.metadata is defaulted to "Metadata()". Hence removed the above line.

2024-01-09 07:35 UTC, sitaram-kalluri commented on packages/at_client/lib/src/transformer/request_transformer/notify_request_transformer.dart
> +    builder.atKey.metadata.ttl = notificationParams.atKey.metadata.ttl;
The fields of AtKey and Metadata are now substituted with AtKey instances in all verb builders. The metadata values are assigned to the metadata fields in the atKey.metadata.

2024-01-09 07:36 UTC, sitaram-kalluri commented on packages/at_client/lib/src/transformer/response_transformer/get_response_transformer.dart
> +    if (tuple.one.metadata.isBinary) {
Since in AtKey.metadata is defaulted to "Metadata()" and boolean fields in metadata have default values, removed null check.

2024-01-09 07:41 UTC, sitaram-kalluri commented on packages/at_client/lib/src/transformer/response_transformer/notification_response_transformer.dart
> +    if (atNotification.metadata != null) {
Since AtKey.metadata does not hold null value, added a null check before assigning the metadata.

2024-01-09 07:46 UTC, sitaram-kalluri commented
> This PR has a **lot** of files changed
> 
> Via the "Files Changed" tab), please add a brief explanation of the reason for each change (at least the first time it appears - e.g. the change from `atKey.key ?? ''` to `atKey.key` appears in many place - please explain why.)
> 
> Please also consider for every change here whether it is a breaking change for the at_client package

@gkc: Added comments explaining the changes. We have ensured not to introduce any breaking changes. @purnimavenkatasubbu  has completed a round of testing with mobile apps with this branch and no bugs are reported.

2024-01-09 12:45 UTC, gkc commented on packages/at_client/lib/src/client/at_client_impl.dart
> -      keyWithNamespace = AtClientUtil.getKeyWithNameSpace(atKey, _preference!);
Why is the namespace fixing no longer required?

2024-01-09 12:54 UTC, gkc commented on packages/at_client/lib/src/transformer/request_transformer/put_request_transformer.dart
> +      ..atKey = (AtKey()
Why are you creating a new atKey object here? Can't we just use the one that was passed as a method parameter?

2024-01-09 12:57 UTC, gkc requested changes
A few more requests and comments

2024-01-09 12:58 UTC, gkc commented
> > This PR has a **lot** of files changed
> > Via the "Files Changed" tab), please add a brief explanation of the reason for each change (at least the first time it appears - e.g. the change from `atKey.key ?? ''` to `atKey.key` appears in many place - please explain why.)
> > Please also consider for every change here whether it is a breaking change for the at_client package
> 
> @gkc: Added comments explaining the changes. We have ensured not to introduce any breaking changes. @purnimavenkatasubbu has completed a round of testing with mobile apps with this branch and no bugs are reported.

Thank you both

2024-01-10 08:09 UTC, sitaram-kalluri commented on packages/at_client/lib/src/client/at_client_impl.dart
> -      keyWithNamespace = AtClientUtil.getKeyWithNameSpace(atKey, _preference!);
By assigning atKey directly to the verb builder, key construction utilizes AtKey.toString(), appending the namespace to the key. For the key we do not want namespace to be appended, leaving the namespace fields unset or initializing them to an empty string will suffice.

However, when the user doesn't set a namespace for the AtKey, the earlier practice involved appending the namespace from the AtClientPreferences when namespaceAware is set to "true" is missing here. Will add the code where if atKey.namespace is null or empty and namespaceAware is true, then set the namespace from AtClientPreference.namespace

2024-01-11 10:22 UTC, sitaram-kalluri commented on packages/at_client/lib/src/transformer/request_transformer/put_request_transformer.dart
> +      ..atKey = (AtKey()
The AtKey received from the put method is assigned to the UpdateVerbBuilder.atKey. Removed the above because we not have assign each field of atKey to the atKey in UpdateVerbBuilder.

2024-01-12 11:19 UTC, gkc requested changes
@sitaram-kalluri @purnimavenkatasubbu Please can you do another round of testing of atmospherePro, atBuzz and at_talk with this branch, just to make sure

2024-01-12 11:33 UTC, sitaram-kalluri commented
> @sitaram-kalluri @purnimavenkatasubbu Please can you do another round of testing of atmospherePro, atBuzz and at_talk with this branch, just to make sure

@gkc : Sure, will do a round of testing with apps and keep you updated.

2024-01-12 17:36 UTC, purnimavenkatasubbu commented
I did a quick round of sanity testing with atMospherePro, atBuzz, and atTalk pointing to this branch of at_client. It looks good. Attaching below POTs
[atBuzzLogsUpdateAtClientDependencies12th.txt](https://github.com/atsign-foundation/at_client_sdk/files/13922365/atBuzzLogsUpdateAtClientDependencies12th.txt)
[atmospherePRoUpdateAtClientDependencies12Jan.txt](https://github.com/atsign-foundation/at_client_sdk/files/13922366/atmospherePRoUpda
![Screenshot from 2024-01-12 23-01-14](https://github.com/atsign-foundation/at_client_sdk/assets/43639593/2d9c5282-f104-4914-b3e0-758f6b4d2d61)
![Screenshot from 2024-01-12 23-01-23](https://github.com/atsign-foundation/at_client_sdk/assets/43639593/19852fe1-8e86-4a6e-944f-8c2d50e0812c)
teAtClientDependencies12Jan.txt)

2024-01-13 18:31 UTC, gkc submitted a review, later dismissed

2024-01-16 09:31 UTC, gkc approved these changes

2024-01-16 09:31 UTC, merged