feat: Introduce methods to set SPP and fetch OTP from the secondary server
atsign-foundation/at_client_sdk pull request #1223
Opened 2024-01-25 07:04 UTC by sitaram-kalluri

**- What I did**
- Introduce "setSPP" and "getOTP" methods in at_client_spec to set the semi permanent pass-code and fetch the OTP from the secondary server.
- Introduce "enrollmentId" as optional parameter to AtClient.create method and AtClient._init method to set the enrollment Id which will be propagated to the AtLookup instance used for APKAM authentication.
- Update the at_demo_data from v1.0.1 to v1.0.3 which has RSA Key-pair added APKAM.
- In the "at_keys_initializer.dart" file, eliminate the dependency on "at_demo_credentials.dart," as it duplicates the content found in the "at_demo_data.dart" file.
- Update the test condition in the enrollment_test.dart - "validate client functionality to fetch pending enrollments on legacy pkam authenticated client"
  The initial condition was 
```
    expect(enrollmentRequests.length, 4);
   // 4 entries - 2 entries from this test
   // + 2 entries from the other test in this file.
```
With this condition, there might be intermitent failure depending on the order of the test run. Hence the condition as follows - `expect(enrollmentRequests.length > 2, true);`

**- How I did it**
- The setSPP method accepts a String which represents an SPP. Performs validations and if successful, sends the SPP to secondary server via the executeCommand, else returns an InvalidPINException.
- The getOTP method fetches the OTP from the secondary server and returns to the client.

**- How to verify it**
- Added unit tests to assert on the negative scenarios that returns InvalidPINException for an Invalid SPP supplied.
- Added functional test to create a new SPP and submit and enrollment request with the SPP.

**- Description for the changelog**
- Introduce methods to set SPP and fetch OTP from the secondary server

2024-01-25 11:18 UTC, gkc reviewed
LGTM - I won't approve, I'll let @murali-shris approve once he has reviewed

2024-01-29 06:12 UTC, murali-shris requested changes

2024-01-29 06:12 UTC, murali-shris commented on packages/at_client/lib/src/client/at_client_spec.dart
> +  ///
document the exception when an unauthorized connection calls setSPP

2024-01-29 06:12 UTC, murali-shris commented on tests/at_functional_test/pubspec.yaml
> +  at_demo_data:
why can't we use published at_demo_data?

2024-01-29 07:54 UTC, sitaram-kalluri commented on tests/at_functional_test/pubspec.yaml
> +  at_demo_data:
Sure Murali, will publish the at_demo_data and update the version here.

2024-02-05 07:45 UTC, murali-shris requested changes

2024-02-05 07:45 UTC, murali-shris commented on packages/at_client/lib/src/client/at_client_impl.dart
> +    this.enrollmentId ??= enrollmentId;
have this line in AtClientImpl._ instead of _init(). you can remove the param to _init

2024-02-05 07:45 UTC, murali-shris commented on packages/at_client/lib/src/client/at_client_impl.dart
> +      throw InvalidPinException(e.errorCode, e.errorMessage);
we have to check the error code and then throw InvalidPinException. It can be any AtLookUpException here

2024-02-05 11:21 UTC, sitaram-kalluri commented on packages/at_client/lib/src/client/at_client_impl.dart
> +    this.enrollmentId ??= enrollmentId;
This is addressed in [38d3293](https://github.com/atsign-foundation/at_client_sdk/pull/1223/commits/38d3293920af315d493a991a59b61eb49e201704)

2024-02-05 11:23 UTC, sitaram-kalluri commented on packages/at_client/lib/src/client/at_client_impl.dart
> +      throw InvalidPinException(e.errorCode, e.errorMessage);
Added validations for the SPP before the invocation of remoteSecondary.executeCommand. So for any invalid pin, the exception will be returned from at_client itself (Calls will not be send to secondary server). Hence converting any exception from secondary server as `AtClientException`

2024-02-06 13:31 UTC, murali-shris approved these changes

2024-02-06 13:51 UTC, merged