feat: APKAM Enrollment changes
atsign-foundation/at_client_sdk pull request #1257
Opened 2024-03-08 07:16 UTC by sitaram-kalluri

**- What I did**
- The PR contains changes related to APKAM feature.
   - at_client : 
      - The AtClient package contains changes to expose the enrollment services to the apps such as to fetch the pending enrollments, approve or deny enrollments.
       - Modify SelfKeyEncryption and SelfKeyDecryption to use at_chops instance to fetch the self encryption key key instead of fetching the key from the local secondary.
  - at_client_mobile: 
      - Introduce "enroll", "getSentEnrollmentRequest" and "getFinalEnrollmentStatus" methods in "AtAuthService" class to support APKAM feature.
      - Remove exporting of the implementation classes in at_client_mobile.
      - Updated the port number's docker compose to publish the newly added atSign ports from the container to the host.

- AtClientMobile :
     - To submit a new enrollment, use "enroll" method in the `AtAuthService.` 
     - After submitting an enrollment, to view the enrollment and to check the status, introduced "getSentEnrollmentRequest" and "getFinalEnrollmentStatus" method in `AtAuthService` respectively.
     - Currently, the implementation classes are exported in `at_client_mobile.dart` file. For example `export 'src/auth/at_auth_service_impl.dart'` is being exported. To prevent this, introduce a new class `AtClientMobile` in `at_client_mobile_base.dart` file . This class contains methods to obtain the instances of implementation classes.

- AtClient: 
   - Introduce a new class "EnrollmentService" which exposes methods to fetch the pending enrollment list, approve and deny the enrollments. The "EnrollmentServiceImpl" class implements the "EnrollmentService".
   - The "fetchEnrollmentRequest" forwards the request to server to get the pending enrollment requests. The "PendingEnrollmentRequest" class encapsulates the enrollment details received from the server.
   - The approve and deny requests are forwarded to to at_auth package which fulfills the request.
   - Update the AtClientManager, AtClientSpec, AtClientImpl classes to set the EnrollmentService instance.
   - In the "SelfKeyEncryption" class, use at_chops to fetch the self encryption key instead of fetching from the local secondary stoage.

- Update the existing unit and functional tests to consume the refactoring changes. 

**- How to verify it**
- Tested the changes with the mobile app.

- In AtClientMobile, when an enrollment is approved, to generate atkeys file we use at_file_saver package, with which we are facing issue with latest version. This is worked by @sachins-geekyants in the following PR: https://github.com/atsign-foundation/at_client_sdk/pull/1276

2024-03-11 10:03 UTC, gkc commented
@sitaram-kalluri will review today thank you!

2024-03-22 11:14 UTC, murali-shris requested changes

2024-03-22 11:14 UTC, murali-shris commented on packages/at_client_mobile/lib/src/auth/at_auth_service_impl.dart
> +      throw InvalidRequestException(
can we through AtEnrollmentException here? InvalidRequestException is an exception from secondary server

2024-03-28 10:57 UTC, murali-shris requested changes

2024-03-28 10:57 UTC, murali-shris commented on packages/at_client/lib/src/encryption_service/self_key_encryption.dart
> -    var selfEncryptionKey =
these changes from trunk related to replacing EncryptionUtil methods should not be removed.

2024-04-01 12:51 UTC, gkc commented
@sitaram-kalluri This PR is not ready for review. Please ping me once you have addressed @murali-shris's requests and the functional tests are passing

2024-04-01 12:51 UTC, gkc requested changes
Tests are not passing

2024-04-01 15:57 UTC, sitaram-kalluri commented on packages/at_client/lib/src/encryption_service/self_key_encryption.dart
> -    var selfEncryptionKey =
The changes are addressed are in https://github.com/atsign-foundation/at_client_sdk/pull/1257/commits/2c3ea9768b9a158ce02499cfe3d836ed3735bae7

2024-04-01 15:57 UTC, sitaram-kalluri commented on packages/at_client_mobile/lib/src/auth/at_auth_service_impl.dart
> +      throw InvalidRequestException(
The changes are addressed are in https://github.com/atsign-foundation/at_client_sdk/pull/1257/commits/2c3ea9768b9a158ce02499cfe3d836ed3735bae7

2024-04-01 16:02 UTC, sitaram-kalluri commented
> @sitaram-kalluri This PR is not ready for review. Please ping me once you have addressed @murali-shris's requests and the functional tests are passing

@gkc: The review comments are addressed and updated with the latest trunk branch code.

Pending work: Once enrollment is approved, securely store the keys in the keychain manager being worked by @sachins-geekyants. Therefore, the PR is still marked as draft..

2024-04-01 17:50 UTC, murali-shris approved these changes

2024-04-01 17:55 UTC, murali-shris requested changes

2024-04-01 17:55 UTC, murali-shris commented on packages/at_client/pubspec.yaml
> +dependency_overrides:
publish at_auth and replace with the published version

2024-04-03 10:15 UTC, sitaram-kalluri commented on packages/at_client/pubspec.yaml
> +dependency_overrides:
Published at_auth 2.0.0 and updated in pubspec.yaml

2024-04-04 11:37 UTC, gkc commented
@sitaram-kalluri Have you tested with other things that use the at_client package e.g. at_talk, the various demos in at_demos, noports, etc?

2024-04-04 11:38 UTC, gkc commented
> > @sitaram-kalluri This PR is not ready for review. Please ping me once you have addressed @murali-shris's requests and the functional tests are passing
> 
> @gkc: The review comments are addressed and updated with the latest trunk branch code.
> 
> Pending work: Once enrollment is approved, securely store the keys in the keychain manager being worked by @sachins-geekyants. Therefore, the PR is still marked as draft..

@sitaram-kalluri  Since the PR is no longer marked as 'draft', can I presume that the Pending work you mention has been completed?

2024-04-04 11:43 UTC, gkc commented on packages/at_client/lib/src/preference/at_client_preference.dart
> +  bool enableEnrollmentDuringOnboard = false;
This variable is not well named. The name suggests that you are enabling enrollment during onboarding (which I don't think I understand either) - but the comment says 'the onboarded app will get privilege to approve enrollment requests' ... couple of other questions though
1. This instance variable doesn't appear to be used anywhere in the at_client package. Why is it here at all?
2. What does this actually control and how does it work? Where is the logic that uses this variable?

2024-04-04 11:48 UTC, gkc commented on packages/at_client/lib/src/preference/at_client_preference.dart
> +  bool enableEnrollmentDuringOnboard = false;
I've partially answered my own questions
1. This variable is also declared in the AtOnboardingPreference of the at_onboarding_cli package, which extends AtClientPreference. It should therefore I imagine be removed from AtClientPreference
2. at_onboarding_cli package has explanation and some tests. I would still assert that it is not a well-named variable but we can address that later

2024-04-04 11:52 UTC, gkc commented on packages/at_client/lib/src/preference/at_client_preference.dart
> +  bool enableEnrollmentDuringOnboard = false;
A third question that occurs is - is there logic in the at_auth package which implements the same kind of logic as exists in the at_onboarding_cli package with regards to `enableEnrollmentDuringOnboard` ? If not, why not? is the logic on at_onboarding_cli obsolete?

2024-04-04 11:58 UTC, gkc requested changes
Left some comments and questions but mostly lgtm

2024-04-08 12:31 UTC, sitaram-kalluri commented on packages/at_client/lib/src/preference/at_client_preference.dart
> +  bool enableEnrollmentDuringOnboard = false;
Removed "enableEnrollmentDuringOnboard" variable from AtClientPreferences

2024-04-08 14:36 UTC, sitaram-kalluri commented
@gkc : Completed testing with at_talk and no-ports and works fine. Attaching the log

NoPorts Log : [no-ports.log](https://github.com/atsign-foundation/at_client_sdk/files/14905846/no-ports.log)
at_talk Log : ![at_talk_log](https://github.com/atsign-foundation/at_client_sdk/assets/16645698/6409d549-4686-490c-8cb2-b8ad860b3f28)

2024-04-09 13:00 UTC, gkc submitted a review, later dismissed
LGTM. Thank you @sitaram-kalluri

2024-04-11 06:58 UTC, murali-shris approved these changes, later dismissed

2024-04-11 10:03 UTC, gkc commented
@sitaram-kalluri  Functional tests failing on this test
```
❌ loading test/enrollment_test.dart (failed)
  Failed to load "test/enrollment_test.dart":
  test/enrollment_test.dart:309:29: Error: Method not found: 'FirstEnrollmentRequest'.
      var enrollmentRequest = FirstEnrollmentRequest(
                              ^^^^^^^^^^^^^^^^^^^^^^
```

2024-04-11 10:28 UTC, sitaram-kalluri commented
> @sitaram-kalluri Functional tests failing on this test
> 
> ```
> ❌ loading test/enrollment_test.dart (failed)
>   Failed to load "test/enrollment_test.dart":
>   test/enrollment_test.dart:309:29: Error: Method not found: 'FirstEnrollmentRequest'.
>       var enrollmentRequest = FirstEnrollmentRequest(
>                               ^^^^^^^^^^^^^^^^^^^^^^
> ```

@gkc : The root cause of the failure is very clear. The "FirstEnrollmentRequest" class is not exported in the at_auth package. We did not export the class because apps will not use the FirstEnrollmentRequest. Apps will invoke the onboard method, which will internally submit the FirstEnrollmentRequest. 

Something that is strange is how did tests pass till now and why the issue occur now? Will debug on this and keep it updated.

2024-04-11 12:00 UTC, murali-shris approved these changes

2024-04-11 12:05 UTC, sitaram-kalluri commented
> > @sitaram-kalluri Functional tests failing on this test
> > ```
> > ❌ loading test/enrollment_test.dart (failed)
> >   Failed to load "test/enrollment_test.dart":
> >   test/enrollment_test.dart:309:29: Error: Method not found: 'FirstEnrollmentRequest'.
> >       var enrollmentRequest = FirstEnrollmentRequest(
> >                               ^^^^^^^^^^^^^^^^^^^^^^
> > ```
> 
> @gkc : The root cause of the failure is very clear. The "FirstEnrollmentRequest" class is not exported in the at_auth package. We did not export the class because apps will not use the FirstEnrollmentRequest. Apps will invoke the onboard method, which will internally submit the FirstEnrollmentRequest.
> 
> Something that is strange is how did tests pass till now and why the issue occur now? Will debug on this and keep it updated.

@gkc : The issue is fixed. The issue occurs because a particular test is modified to use "FirstEnrollmentRequest". Reverted the change and modified the test as it was before.

2024-04-11 13:10 UTC, gkc commented
> > > @sitaram-kalluri Functional tests failing on this test
> 
> > > ```
> 
> > > ❌ loading test/enrollment_test.dart (failed)
> 
> > >   Failed to load "test/enrollment_test.dart":
> 
> > >   test/enrollment_test.dart:309:29: Error: Method not found: 'FirstEnrollmentRequest'.
> 
> > >       var enrollmentRequest = FirstEnrollmentRequest(
> 
> > >                               ^^^^^^^^^^^^^^^^^^^^^^
> 
> > > ```
> 
> > 
> 
> > @gkc : The root cause of the failure is very clear. The "FirstEnrollmentRequest" class is not exported in the at_auth package. We did not export the class because apps will not use the FirstEnrollmentRequest. Apps will invoke the onboard method, which will internally submit the FirstEnrollmentRequest.
> 
> > 
> 
> > Something that is strange is how did tests pass till now and why the issue occur now? Will debug on this and keep it updated.
> 
> 
> 
> @gkc : The issue is fixed. The issue occurs because a particular test is modified to use "FirstEnrollmentRequest". Reverted the change and modified the test as it was before. 

👍 thanks @sitaram-kalluri

2024-04-11 13:42 UTC, merged