feat: enhance EnrollmentService.fetchEnrollmentRequests() to filter enrollment requests
atsign-foundation/at_client_sdk pull request #1264
Opened 2024-03-19 11:16 UTC by srieteja

**- What I did**
- introduce new param 'enrollmentStatusFilter' in EnrollListRequestParam class
- use the above param in EnrollmentService.fetchEnrollmentRequests() to build the command that lists only enrollment requests that match the filter.

**- How I did it**
- EnrollListRequestParam.enrollmentStatusFilter will be used by users to pass the desired enrollment statuses they wish to list.
- EnrollmentService.fetchEnrollmentRequests() will use this filter to construct a relevant command which will be passed to the server.

**- How to verify it**
- unit test added, that verifies that appropriate command is generated using the EnrollVerbBuilder and the parsing of response from the server.
- Yet to evaluate if a functional test is needed to validate the change

**- Description for the changelog**

feat: enhance EnrollmentService.fetchEnrollmentRequests() to filter enrollment requests

2024-03-20 03:10 UTC, sitaram-kalluri requested changes

2024-03-20 03:10 UTC, sitaram-kalluri commented on tests/at_functional_test/test/enrollment_test.dart
> +        'enroll:request:{"appName":"new_app","deviceName":"pixel","namespaces":{"new_app":"rw"},"otp":"$otp","apkamPublicKey":"$apkamPublicKey","enrollmentStatusFilter":["pending"]}');
Please have tests for EnrollmentStatus.APPROVED. And also a test which has two enrollment statues - Pending and Approved.

2024-03-20 03:10 UTC, sitaram-kalluri commented on packages/at_client/lib/src/util/enroll_list_request_param.dart
> +  List<EnrollmentStatus>? enrollmentListFilter;
Default it all Enrollment statuses

2024-03-20 03:10 UTC, sitaram-kalluri commented on packages/at_client/lib/src/service/enrollment_service_impl.dart
> +    if (enrollmentListParams?.enrollmentListFilter != null) {
Since enrollmentListFilter is defaulted all values, this IF condition is not required.

2024-03-20 09:00 UTC, srieteja commented on packages/at_client/lib/src/util/enroll_list_request_param.dart
> +  List<EnrollmentStatus>? enrollmentListFilter;
change made as part of [fad329f](https://github.com/atsign-foundation/at_client_sdk/pull/1264/commits/fad329fba6413c335ed531b514a27b361e2bc2b4)

2024-03-20 09:00 UTC, srieteja commented on packages/at_client/lib/src/service/enrollment_service_impl.dart
> +    if (enrollmentListParams?.enrollmentListFilter != null) {
change made as part of [fad329f](https://github.com/atsign-foundation/at_client_sdk/pull/1264/commits/fad329fba6413c335ed531b514a27b361e2bc2b4)

2024-03-20 09:00 UTC, srieteja commented on tests/at_functional_test/test/enrollment_test.dart
> +        'enroll:request:{"appName":"new_app","deviceName":"pixel","namespaces":{"new_app":"rw"},"otp":"$otp","apkamPublicKey":"$apkamPublicKey","enrollmentStatusFilter":["pending"]}');
change made as part of [fad329f](https://github.com/atsign-foundation/at_client_sdk/pull/1264/commits/fad329fba6413c335ed531b514a27b361e2bc2b4)

2024-03-22 14:15 UTC, srieteja commented
Making this a draft PR until changes in https://github.com/atsign-foundation/at_libraries/pull/530 and https://github.com/atsign-foundation/at_libraries/pull/536 have been consumed by AtServer and that version of AtServer has been promoted to Prod. This measure is being taken to prevent any backwards compatibility issues.

2024-04-11 13:42 UTC, closed without merging