fix: Skip cached public keys and cached shared keys from enrollment a…
atsign-foundation/at_client_sdk pull request #1334
Opened 2024-06-11 12:22 UTC by sitaram-kalluri

…uthorization check

**- What I did**
 - When authenticated with APKAM, operations performed in a local secondary database exclude only reserved keys from validation. However, there is an issue with validating the cached `sharedkey`and `encryption public key`because these keys lack a namespace for validation.
 - Along with the reserved keys, exclude the cached shared_key and cached public key from the enrollment authorization check.

**- How I did it**
In local_secondary.dart, modify the existing method which excludes the local keys from enrollment authorization check to also exclude the cached `sharedkey` and `encryption public key`.

**- How to verify it**
- All the existing unit and functional test should pass.
- Tested the no-ports E2E tests locally with APKAM authentication.

Attaching the test logs
[srvd.log](https://github.com/user-attachments/files/15787816/srvd.log)
[sshnp.log](https://github.com/user-attachments/files/15787817/sshnp.log)
[sshnpd.log](https://github.com/user-attachments/files/15787818/sshnpd.log)

Pending work:
- Add unit tests to ensure the cached shared key, cached public key and reserved keys are excluded from enrollment authorization check. Created a git issue and working on it : https://github.com/atsign-foundation/at_client_sdk/issues/1335

2024-06-12 05:40 UTC, murali-shris commented
is there any test which covers these changes?

2024-06-12 06:12 UTC, sitaram-kalluri commented
> is there any test which covers these changes?

Created a git issue, working on the changes.

2024-06-12 11:52 UTC, sitaram-kalluri commented
> > is there any test which covers these changes?
> 
> Created a git issue, working on the changes.

Completed adding of unit tests.

2024-06-12 22:26 UTC, gkc requested changes
Please add tests which explicitly assert behaviour of LocalSecondary.isEnrollmentAuthorizedForOperation for a variety of verbs and keys

e.g. llookup for `cached:@alice:shared_key@bob`, `cached:@alice:key.in.any.name.space@bob`, `cached:@alice:foo@bob` as well as their non-cached equivalents; and also add tests for updates and deletes and notify

I suggest you modify LocalSecondary renaming _enrollment to enrollment and making it `@visibleForTesting` to make it possible to write many small test cases like this
```
    test('test llookup on cached:@alice:shared_key@bob', () async {
      final testEnrollmentId = 'aaa111';

      LocalSecondary ls = 
      <do setup of a LocalSecondary in a test setup function>

      ls.enrollment = Enrollment()
        ..enrollmentId = testEnrollmentId
        ..appName = 'testApkamAuthCachedLLookup'
        ..deviceName = 'testDevice'
        ..namespace = {"fubar": "rw"};

      final bool authorized = await ls.isEnrollmentAuthorizedForOperation(
          'cached:@alice:shared_key@bob', LLookupVerbBuilder());
      expect (authorized, true);
    });

```

2024-06-12 22:26 UTC, gkc commented on packages/at_client/test/test_utils/test_utils.dart
>  class TestUtils {
Instead of hard-coding keys, please generate them during test setup

2024-06-14 01:55 UTC, sitaram-kalluri commented on packages/at_client/test/test_utils/test_utils.dart
>  class TestUtils {
Removed the hard-coded keys. Keys are generated during the running of the test.

2024-06-14 01:56 UTC, sitaram-kalluri commented
> Please add tests which explicitly assert behaviour of LocalSecondary.isEnrollmentAuthorizedForOperation for a variety of verbs and keys
> 
> e.g. llookup for `cached:@alice:shared_key@bob`, `cached:@alice:key.in.any.name.space@bob`, `cached:@alice:foo@bob` as well as their non-cached equivalents; and also add tests for updates and deletes and notify
> 
> I suggest you modify LocalSecondary renaming _enrollment to enrollment and making it `@visibleForTesting` to make it possible to write many small test cases like this
> 
> ```
>     test('test llookup on cached:@alice:shared_key@bob', () async {
>       final testEnrollmentId = 'aaa111';
> 
>       LocalSecondary ls = 
>       <do setup of a LocalSecondary in a test setup function>
> 
>       ls.enrollment = Enrollment()
>         ..enrollmentId = testEnrollmentId
>         ..appName = 'testApkamAuthCachedLLookup'
>         ..deviceName = 'testDevice'
>         ..namespace = {"fubar": "rw"};
> 
>       final bool authorized = await ls.isEnrollmentAuthorizedForOperation(
>           'cached:@alice:shared_key@bob', LLookupVerbBuilder());
>       expect (authorized, true);
>     });
> ```

Added unit tests to assert the "isEnrollmentAuthorizedForOperation" method.

2024-06-14 07:58 UTC, gkc commented on packages/at_client/lib/src/client/local_secondary.dart
> +  @visibleForTesting
This can continue to be fully visible

2024-06-14 08:48 UTC, sitaram-kalluri commented on packages/at_client/lib/src/client/local_secondary.dart
> +  @visibleForTesting
Removed the annotation and pushed the changes.

2024-06-14 09:10 UTC, gkc approved these changes

2024-06-14 09:11 UTC, merged