removing .env file from at_client_sdk example
atsign-foundation/at_client_sdk pull request #476
Opened 2022-04-07 15:17 UTC by srieteja

… add the .env file through README.md

**- What I did**
removed .env file from pubspec.yaml. Added instructions to create an env file through readme.md

2022-04-07 15:43 UTC, gkc requested changes
I would like more than just adding to the readme, if possible - ideally something that during build will alert the developer that they need a .env file, and point them to the readme

2022-04-21 09:12 UTC, srieteja commented
@gkc I have upgraded the versions of kotlin, build tools and at_app_flutter. The app now works smoothly with an env file present. @Intiserahmed has also reported the example app to be working properly now.

2022-04-22 12:32 UTC, kalluriramkumar approved these changes

2022-04-25 07:57 UTC, gkc commented
> I have upgraded the versions of kotlin, build tools and at_app_flutter. The app now works smoothly with an env file present. @Intiserahmed has also reported the example app to be working properly now. @gkc does the example app still need to assert the presence of an env file?

If @Intiserahmed is happy with it then I think this is good enough - thanks @srieteja

2022-04-25 07:58 UTC, gkc approved these changes

2022-04-25 08:26 UTC, merged