Implement exception handling for put request
atsign-foundation/at_client_sdk pull request #515
Opened 2022-05-17 04:27 UTC by kalluriramkumar

**- What I did**
Add exception chaining to put method in AtClient Impl

**- How I did it**

**- How to verify it**

**- Description for the changelog**

2022-05-17 08:45 UTC, murali-shris commented on at_client/lib/src/client/at_client_impl.dart
> +      if (putResponse == null || putResponse.isEmpty) {
should this check be in put transfomer?

2022-05-17 08:45 UTC, murali-shris commented on at_client/lib/src/client/remote_secondary.dart
> +    }on AtException catch (e) {
formatting issue

2022-05-17 10:27 UTC, gkc requested changes
LGTM. Will not approve yet as we need to not merge any new changes into trunk until https://github.com/atsign-foundation/at_client_sdk/pull/514 has been fully tested, merged into trunk and new version of at_client package published

2022-06-06 04:27 UTC, murali-shris approved these changes

2022-06-06 05:01 UTC, kalluriramkumar commented
> LGTM. Will not approve yet as we need to not merge any new changes into trunk until #514 has been fully tested, merged into trunk and new version of at_client package published

@gkc : We have published the at_client version which has PR 514. Can you please review the PR once again.

2022-06-06 09:36 UTC, gkc approved these changes

2022-06-06 09:36 UTC, merged