Fix sync issue on atsign reset
atsign-foundation/at_client_sdk pull request #545
Opened 2022-06-08 04:58 UTC by kalluriramkumar

**- What I did**
1. Sync the local changes to server when server is reset.
2. Refactor the sync_service_impl.dart file to write unit test
3. Write unit test for server reset scenario.

**- How I did it**
If localCommitId is greater than serverCommitId indicates server is reset (In other conditions localCommitId is either equal or less than serverCommitId). then set localSeqNumber to serverCommitId to get all the changes to sync to server.

**- How to verify it**
Pair the atsign with in mobile app and reset the server. Upon activation the data should be sync'ed back to server.

**- Description for the changelog**

2022-06-08 09:32 UTC, gkc commented
I don't think we should proceed with this approach.
1) We can have a backup automatically taken of a server's data as part of the deletion process, which can then be automatically recovered
2) The approach in this PR will not work for multiple clients each with fragments of the data due to commit ID clashes. We could try to have the server mediate all of this and go into a 'recovery' mode but this is very very complex
3) If we really want to have automatic reconstruction of server data from clients (e.g. in the event of catastrophic data loss on the server followed by recovery from backup up to 24 hours old) then that is _far_ more easily done with a sync-via-timestamp rather than sync-via-CommitID approach

2022-06-08 09:35 UTC, gkc requested changes
See [this comment](https://github.com/atsign-foundation/at_client_sdk/pull/545#issuecomment-1149686341)

2022-06-14 10:09 UTC, kalluriramkumar commented
@gkc : Can you please let me know if we can close this PR?

2022-06-15 11:39 UTC, gkc commented
@kalluriramkumar : Please close whenever you wish. @VJag has started a document to talk about desired behaviour in all of the different possible reset / data loss scenarios. That document should include a reference to this PR.

2022-06-15 13:08 UTC, kalluriramkumar commented
> @kalluriramkumar : Please close whenever you wish. @VJag has started a document to talk about desired behaviour in all of the different possible reset / data loss scenarios. That document should include a reference to this PR.

Sure Gary, Thank you.

2022-06-15 13:08 UTC, closed without merging