fix: do not sync cached keys to cloud secondary
atsign-foundation/at_client_sdk pull request #602
Opened 2022-07-13 10:23 UTC by kalluriramkumar

**- What I did**
1. Modify the sync logic to skip the cached keys being sync'ed to cloud secondary.

**- How I did it**
1. Add an IF condition what checks if key starts with `cached:`. If yes, ignores the key to sync-batch request that is sent to cloud secondary.

**- How to verify it**

**- Description for the changelog**

2022-07-13 10:30 UTC, gkc requested changes

2022-07-13 10:30 UTC, gkc commented on at_client/lib/src/service/sync_service_impl.dart
> +      //Skipping the cached keys to sync to cloud secondary.
1) Why are we skipping here rather than when we are getting the list of uncommitted entries?
2) What happens to the uncommitted entries which are for "cached:"
3) Should we actively prevent updates via LocalSecondary to entries which are "cached:" ?

2022-07-13 11:21 UTC, gkc commented on at_client/lib/src/service/sync_service_impl.dart
> +      //Skipping the cached keys to sync to cloud secondary.
After discussion:

1: It's fine to skip here
2: Handled by logic around lastSyncedEntryCacheMap and SyncUtil.getLastSyncedEntry; no issue here, we won't get these uncommitted entries again

3. We should add logic to AtClientImpl.put() which checks key structure (starts with 'cached:') as well as what it currently does, which is check metadata.isCached

2022-07-14 14:51 UTC, sitaram-kalluri commented
The changes are merged in PR 603

2022-07-14 14:51 UTC, closed without merging