feat: new data structure saved in keychain
atsign-foundation/at_client_sdk pull request #612
Opened 2022-07-19 06:18 UTC by sonle-geekyants

**- What I did**
Upgrade data structure saved in Keychain to fix this ticket [#468](https://github.com/atsign-foundation/apps/issues/468)
**- How I did it**

**- How to verify it**

**- Description for the changelog**

2022-07-20 10:27 UTC, gkc requested changes
Looks OK to me but I'm not expert in the flutter world. Perhaps @XavierChanth you can take a look at this PR also?

My main nit with the PR is that there is a lot of dead code which has been commented-out rather than deleted from the files. Please delete dead code. We use our version control systems to see code diffs. When dead code is removed, then the diffs are easier to read for reviewers, and we don't need a second PR later simply to remove the commented-out code.

2022-07-20 10:27 UTC, gkc commented on at_client_mobile/example/lib/src/screens/login.dart
> +                  // );
Please delete dead code.

2022-07-20 10:27 UTC, gkc commented on at_client_mobile/lib/src/at_client_auth.dart
> +        // await _keyChainManager.getValue(atSign, keychainEncryptionPrivateKey);
please delete dead code

2022-07-20 10:27 UTC, gkc commented on at_client_mobile/lib/src/at_client_auth.dart
> +          await _keyChainManager.storeAtSign(atSign: atSignItem);
again, please delete dead code above

2022-07-20 10:27 UTC, gkc commented on at_client_mobile/lib/src/at_client_service.dart
> +    //     atsign, keychainEncryptionPublicKey, encryptionPublicKey);
delete dead code

2022-07-20 10:27 UTC, gkc commented on at_client_mobile/lib/src/at_client_service.dart
> +
delete dead code

2022-07-20 10:27 UTC, gkc commented on at_client_mobile/lib/src/at_client_service.dart
> +    //     await _keyChainManager.getValue(atSign, keychainEncryptionPublicKey);
delete dead code

2022-07-20 10:27 UTC, gkc commented on at_client_mobile/lib/src/at_client_service.dart
> +    // return await _keyChainManager.getValue(atsign, keychainSelfEncryptionKey);
delete dead code

2022-07-20 10:46 UTC, yahu1031 commented
I have used this branch and tested it with the new flutter project. But looks like we still need to fix flutter_keychain first. But we can still push this code to trunk but not good for publish.

2022-07-20 16:56 UTC, XavierChanth requested changes

2022-07-20 16:56 UTC, XavierChanth commented on at_client_mobile/lib/src/at_client_auth.dart
> +import 'atsign_key.dart';
Try to be consistent with import conventions.

2022-07-20 16:56 UTC, XavierChanth commented on at_client_mobile/lib/src/at_client_service.dart
> +import 'atsign_key.dart';
import conventions

2022-07-20 16:56 UTC, XavierChanth commented on at_client_mobile/lib/src/keychain_manager.dart
> +      return null;
delete redundant return statement

2022-07-20 16:56 UTC, XavierChanth commented on at_client_mobile/lib/src/atsign_key.dart
> +  final String name;
'name' should really be called 'atSign'

2022-07-20 16:58 UTC, XavierChanth commented
Please try to use more guard clauses, this will increase readability of the code.

2022-07-21 06:45 UTC, sonle-geekyants commented
Thanks, @gkc @yahu1031, and @XavierChanth 
I've pushed a new commit to solve your comments. please help me check again!

2022-07-21 08:38 UTC, gkc requested changes
Thanks Son for deleting all that dead code. Much easier to follow the diffs now.

I've added some requests for a few new changes

2022-07-21 08:38 UTC, gkc commented on at_client_mobile/example/lib/src/screens/login.dart
> +                    // TODO: Handle this case.
You need to ... handle this case!

2022-07-21 08:38 UTC, gkc commented on at_client_mobile/example/lib/src/screens/login.dart
> +                    // TODO: Handle this case.
You need to ... handle this case!

2022-07-21 08:38 UTC, gkc commented on at_client_mobile/example/lib/src/screens/login.dart
> +                      // TODO: Handle this case.
You need to ... handle this case!

2022-07-21 08:38 UTC, gkc commented on at_client_mobile/example/lib/src/screens/login.dart
> +                      // TODO: Handle this case.
You need to ... handle this case!

2022-07-21 08:38 UTC, gkc commented on at_client_mobile/lib/src/at_client_auth.dart
> +            encryptionPublicKey: encryptionPubKey,
For consistency, please replace the above line with `encryptionPublicKey: encryptionKeyPair.publicKey.toString();` (and remove the now unused `encryptionPubKey` local variable)

2022-07-22 06:42 UTC, sonle-geekyants commented
Thanks @gkc 
I've upgraded the example project with the newest flutter version and corrected the code base on your comments. Please help me check it again!

2022-07-26 06:42 UTC, sonle-geekyants commented
Hi @gkc and @XavierChanth,
Could you please recheck the PR?

2022-07-26 08:38 UTC, XavierChanth approved these changes

2022-07-28 06:20 UTC, sonle-geekyants commented
@gkc please approve this PR and we will prepare to release it.

2022-07-28 06:50 UTC, gkc approved these changes
👍👍

2022-07-28 06:52 UTC, merged