fix: revert deleted function
atsign-foundation/at_client_sdk pull request #646
Opened 2022-08-09 09:25 UTC by sonle-geekyants

**- What I did**
Because we lost some functions in at_client_mobile when upgrading the data structure, I bring back all of them back
**- How I did it**
Add deleted functions and make it compatible with the now at_client_mobile version.
**- How to verify it**
Should review my code and try out on your app
**- Description for the changelog**

2022-08-09 13:30 UTC, XavierChanth requested changes
These changes also need to be made to ensure backwards compatibility:

`Future<bool> resetAtSignFromKeychain({required String atsign})`
needs to be changed to positional parameter format
`Future<bool> resetAtSignFromKeychain(String atsign)`

`Future<String?> getSecretFromKeychain(String atsign)`
previously returned a `Future<String>`
...maybe an empty string is an appropriate fallback value for when it is null?

2022-08-09 13:30 UTC, XavierChanth commented on at_client_mobile/lib/src/keychain_manager.dart
> +  Future<Map<String, bool?>> checkForValuesInFlutterKeychain() async {
Mark this as deprecated and to use `getAtsignsWithStatus()` instead.

2022-08-10 13:08 UTC, XavierChanth approved these changes
LGTM, thanks @sonle-geekyants @sachins-geekyants !

2022-08-10 16:25 UTC, murali-shris approved these changes

2022-08-11 09:14 UTC, gkc approved these changes

2022-08-11 12:52 UTC, merged