fix: sync running into loop on invalid keys
atsign-foundation/at_client_sdk pull request #814
Opened 2022-11-24 14:00 UTC by kalluriramkumar

**- What I did**
* Fix the sync infinite loop issue.

**- How I did it**
* At the moment, When the server is ahead of the local secondary, to ensure all the delta commits are received, we run a loop until the localCommitId is equal to serverCommitId.
* The problem with this approach is if an invalid key is not synced to local  secondary, the sync runs into an infinite loop.
* Hence we replaced the `while (serverCommitId > localCommitId)` with `while (serverCommitId > lastReceivedServerCommitId)` so that we run the loop until the lastReceivedServerCommitId is equal to serverCommitId

**- How to verify it**
* The end-to-end tests and the unit tests should pass.

**- Description for the changelog**
* Fix the sync running into an infinite loop when invalid keys do not sync to the local secondary

2022-11-24 16:44 UTC, gkc requested changes

2022-11-24 16:44 UTC, gkc commented on packages/at_client/lib/src/service/sync_service_impl.dart
>        }
LGTM. While we're changing the code here, can you also log the stack trace when we encounter exceptions or errors please

2022-11-25 08:44 UTC, sitaram-kalluri commented on packages/at_client/lib/src/service/sync_service_impl.dart
>        }
Added stack trace to the exception and the error.

2022-11-25 09:23 UTC, gkc approved these changes

2022-11-25 09:52 UTC, merged