fix: invalid pad block issue
atsign-foundation/at_client_sdk pull request #823
Opened 2022-11-28 13:18 UTC by kalluriramkumar

**- What I did**
1. Refactor the `getSharedKey` method in `AbstractAtKeyEncryption` to sync the `encryptedSharedKey` to the cloud secondary if not already synced before sending the notifications.
2. Write unit tests to assert the above functionality
3. Refactor the classes to initialize fields with mock objects when writing unit tests.

**- How I did it**
1. Introduce `isEncryptedSharedKeyInSync` which verifies if the `shared_key` is synced to the cloud secondary. If not synced, runs the update verb to store the shared_key in the cloud secondary.

2. Refactor the `_getSharedWithPublicKey` method which fetches the encryption public key of the sharedWith atSign. 
    - Earlier (prior to caching of public keys) we store to sharedWith atSign's encryption public key as `public.bob@alice` to store the encryption public key of @‎bob in @‎alice atSign. 
    - Now with caching of the public key, upon initial look up the encryption public key, a cached key will be created automatically.      
    - Hence, instead of creating a new key (public.bob@alice), we can utilize the cached key(cached:public:publickey@bob). 
    - Hence removed the piece of code that creates the key (public.bob@alice) and refactor the method that fetches the encryption public key to first look for a cached public key, if not then run a lookup verb to sharedWith atSign.

3. Following are the changes to enable writing unit tests:

   1. Refactor AtKeyEncryptionManager and AtKeyDecryptionManager classes to accept the at_client object and mark them as singleton classes
   2. Add a constructor to LocalKeyDecryption, SharedKeyEncryption and StreamEncryption classes that accept AtClient instance to enable passing mock objects in unit testing.
   3. Remove the static nature of the getSharedKey method and write unit tests around getting the shared key from the local secondary and remote secondary.
   4. Since, LocalKeyDecryption also needs a shared_key to decrypt the value, mark LocalKeyDecryption as a child of AbstractAtKeyEncryption to make the getSharedKey method available for LocalKeyDecryption.
   5. Refactor the existing unit tests to accommodate the above changes.

**- How to verify it**

Following are the unit tests written to assert the above changes:

Tests in encryption_service_test.dart

1. A group of tests related to fetching and decrypting the encrypted shared key
- A test to verify encrypted shared key is fetched from the local secondary and decrypted successfully
- A test to verify encrypted shared key is fetched from remote secondary and decrypted successfully
- A test to verify empty string is returned when the shared key is not found in local and remote secondary

2. A group of tests related to shared_key is synced to the cloud secondary
- A test to verify isEncryptedSharedKeyInSync method returns false when commit id null
- A test to verify isEncryptedSharedKeyInSync method returns true when commit is not null
- A test to verify isEncryptedSharedKeyInSync method returns false when two commit entries exist with commit id null and not null

3. A group of tests related to shared key encryption
- test to verify encryption when the shared key is available
- test to verify encryption when a new shared key is generated
- test to verify exception is thrown when update command fails to store shared_key to remote secondary

Test in notification_service_test.dart
1. A test to verify notification is not sent when the encryption service throws an exception

**- Description for the changelog**

Fix initial notifications throwing pad block issue because "encryptedSharedKey" is not synced to cloud secondary.

2022-11-30 10:33 UTC, gkc requested changes

2022-11-30 10:33 UTC, gkc commented on packages/at_client/lib/src/decryption_service/decryption_manager.dart
> +  static final AtKeyDecryptionManager _singleton =
Please find another way other than introducing a singleton, especially since calling the getInstance() can modify the singleton's state.

2022-11-30 10:34 UTC, gkc commented on packages/at_client/lib/src/decryption_service/decryption_manager.dart
> +  static final AtKeyDecryptionManager _singleton =
PS This refers to both AtKeyEncryptionManager and AtKeyDecryptionManager

2022-12-05 03:42 UTC, kalluriramkumar commented on packages/at_client/lib/src/decryption_service/decryption_manager.dart
> +  static final AtKeyDecryptionManager _singleton =
Removed the singleton nature for AtKeyEncryptionManager and AtKeyDecryptionManager classes.

2022-12-06 09:48 UTC, gkc requested changes

2022-12-06 09:48 UTC, gkc commented on packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart
> +  Future<bool> isEncryptedSharedKeyInSync(AtKey atKey) async {
Since getLatestCommitEntry is an expensive operation (for now) - can you maintain a map of atKeys which have been previously checked and found to be in sync? So then, if the map contains the atKey, you can return true immediately.

2022-12-06 09:48 UTC, gkc commented on packages/at_client/pubspec.yaml
> +      ref: refactor_commit_log
Please can you

either (1) implement getLatestCommitEntry on the current code structure - i.e. while holding off on the refactoring

Or (2) ensure the refactoring is refactoring only - i.e. does not introduce any breaking change

2022-12-06 09:57 UTC, kalluriramkumar commented on packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart
> +  Future<bool> isEncryptedSharedKeyInSync(AtKey atKey) async {
Sure Gary.

2022-12-06 16:06 UTC, kalluriramkumar commented on packages/at_client/pubspec.yaml
> +      ref: refactor_commit_log
@gkc: I have moved the logic to fetch the latest commit entry to `SyncUtil` class in AtClient package. So now, we do not have to touch the at_persistence_secondary_server

2022-12-09 12:43 UTC, gkc commented on packages/at_client/pubspec.yaml
> +      ref: refactor_commit_log
Perfect - thanks Sitaram

2022-12-09 12:45 UTC, gkc commented on packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart
> +  Future<bool> isEncryptedSharedKeyInSync(AtKey atKey) async {
Perfect - thanks Sitaram

2022-12-09 12:46 UTC, gkc approved these changes

2022-12-09 12:56 UTC, merged