feat: client commit log compaction
atsign-foundation/at_client_sdk pull request #855
Opened 2022-12-19 05:41 UTC by kalluriramkumar

**- What I did**
* Introduce client-side commit log compaction

**- How I did it**
* Introduced a corn job in the at_client package that calls the compaction job in the at_persistence_secondary_server package.
* Added method - `getCompactionStats` method to get the last run to commit log compaction stats 

**- How to verify it**
* Update the unit tests in at_persistence_secondary_server with tests that mimic client-side storage.
  - In the PR: https://github.com/atsign-foundation/at_server/pull/950 , packages/at_persistence_secondary_server/test/at_compaction_test.dart contains the unit tests.

* Added unit tests to test `getCompactionStats` feature.

**- Description for the changelog**
* feat: Introduce client side commit log compaction.

TODO: Publish the at_persistence_spec and at_persistence_secondary_server packages and update the version in at_client package.

2023-01-02 09:08 UTC, sitaram-kalluri commented
Following are the review comments from @VJag:
a. Test commit-log compaction with switch atSign -  Tested with two atSigns switching between each other. When an atSign is switched, the new atSign's commit log instance is passed to the compaction job. The existing cron job is re-initialized.

2023-01-09 11:12 UTC, gkc requested changes
* Need automated tests to verify behaviour when switching atSigns
* Can you explain the design rationale for creating a singleton which can act for multiple atSigns versus having an instance per atSign and controlling its lifecycle more explicitly when AtClientManager.setCurrentAtSign is called?

2023-01-09 14:34 UTC, sitaram-kalluri commented
> * Need automated tests to verify behaviour when switching atSigns
> * Can you explain the design rationale for creating a singleton which can act for multiple atSigns versus having an instance per atSign and controlling its lifecycle more explicitly when AtClientManager.setCurrentAtSign is called?

@gkc: The automated tests on switch atSign are in my local branch. I am waiting for https://github.com/atsign-foundation/at_client_sdk/pull/867 to be merged so that I can use the same approach in removing the previous atSign AtClientCommitLogCompaction instances. 

Initial idea is to reuse the AtClientCommitLogCompaction to invoke the scheduled job of compaction. But then I removed the singleton nature of AtClientCommitLogCompaction and the changes are in my local branch.

2023-01-12 09:57 UTC, gkc reviewed
Generally LGTM but before we merge this I'd really like to see an overview of the algorithm, and why the commit log compaction is safe to run on client side even though client-side commit log usage is very different from server-side usage

2023-01-12 11:29 UTC, sitaram-kalluri commented
> Generally LGTM but before we merge this I'd really like to see an overview of the algorithm, and why the commit log compaction is safe to run on client side even though client-side commit log usage is very different from server-side usage

The difference between the client and cloud secondary commit log is, the client commit log will have entries with null commit IDs which are the uncommitted entries yet to sync to the cloud secondary.

```dart
commitLogMap.removeWhere((key, value) => value.commitId == null);
```
Above is a code snippet from CommitLogKeystore.getDuplicateEntries, which is invoked by the CompactionJob to get the duplicate entries. we ignore the entries with null commit IDs and so we remove them from commitLogMap to preserve the entries. At the moment, we did not target removing the multiple entries of the same key in the uncommitted entries list.

Then, the commit IDs are sorted in descending order and get the distinct commit entry of each key with the highest commit ID and remove the remaining entries.
```dart
var sortedKeys = commitLogMap.keys.toList(growable: false)
      ..sort((k1, k2) => _sortByCommitId(commitLogMap[k2], commitLogMap[k1]));
    var tempSet = <String>{};
    var expiredKeys = <int>[];
    for (var entry in sortedKeys) {
      _processEntry(entry, tempSet, expiredKeys, commitLogMap);
    }
    return expiredKeys;
```

2023-01-12 13:00 UTC, gkc requested changes
Couple of changes re version and CHANGELOG (next version will be 3.0.52)

You mentioned in a comment on this PR
> a. Test commit-log compaction with switch atSign - Tested with two atSigns switching between each other. When an atSign is switched, the new atSign's commit log instance is passed to the compaction job. The cron job of previous atSign is paused and the cron job of a new atSign start/resume.
> 
> b. Test with huge size commit log and verify the put operation: Tested with at_client samples and below is the log snippet of the test result.

Please add test (a) to the end-to-end test pack, and add a variation of test (b) to the functional test pack (the variation being, the number of commit log entries such that generation of them and running of the compaction job should all complete within 30 seconds at most.

2023-01-12 13:00 UTC, gkc commented on packages/at_client/CHANGELOG.md
> +- feat: Introduce commit log compaction to keep size of commit log thin
3.0.51 has been published, this change will be in 3.0.52

2023-01-12 13:00 UTC, gkc commented on packages/at_client/lib/src/preference/at_client_config.dart
> +
will need to change to 3.0.52 (here and in pubspec.yaml)

2023-01-19 10:32 UTC, gkc commented
@sitaram-kalluri @purnimavenkatasubbu is this PR ready for re-review?

2023-01-24 03:50 UTC, sitaram-kalluri commented
> @sitaram-kalluri @purnimavenkatasubbu is this PR ready for re-review?

@gkc: Updated the functional tests to execute put operations and sync when compaction is running in asynchronously. Please review the changes.

2023-01-24 23:27 UTC, gkc approved these changes

2023-01-24 23:27 UTC, merged