fix: at_client.putInternal() throws null error
atsign-foundation/at_client_sdk pull request #925
Opened 2023-02-17 20:54 UTC by srieteja

**- What I did**
- remove a null check that can potentially cause a null check error. AtKey.namespace has a null check in putInternal() that is throwing a null check error when a key is created without a namespace.

**- How to verify it**
- when a key is created without namespace it should not be throwing an exception.
- further assertion in tests on the way

**- Description for the changelog**

fix: at_client.putInternal() throws null error

2023-02-17 21:44 UTC, gkc commented
@srieteja I've pushed a change which I think resolves this issue cleanly. Please take a look

2023-02-18 22:04 UTC, srieteja commented
@gkc calling toString() on AtKey will convert the key and it's parts to lowercase. For the sake of this if-clause we have to preserve the case of AtKey.

2023-02-18 22:12 UTC, srieteja commented
One thing that's bugging me is that there is a verifyPutRequest() before this if-clause, which should throw an exception if the namespace is null. With that check present the control flow should not trigger this if-clause for an AtKey with 'null' namespace.

2023-02-18 22:15 UTC, gkc commented
> One thing that's bugging me is that there is a verifyPutRequest() before this if-clause, which should throw an exception if the namespace is null. With that check present the control flow should not trigger this if-clause for an AtKey with 'null' namespace.

It is perfectly OK for namespace to be null

2023-02-18 22:23 UTC, gkc commented
> @gkc calling toString() on AtKey will convert the key and it's parts to lowercase. For the sake of this if-clause we have to preserve the case of AtKey.

Gotcha. Have pushed a change which reverts to the original but includes a null check

2023-02-18 22:45 UTC, gkc requested changes
Please
1. Update pubspec, changelog and AtClientConfig
2. Add at least two unit tests (one with a null namespace, the other with a non-null namespace which contains some upper-case chars) which prove the change works.

2023-02-19 10:02 UTC, gkc requested changes
Unit tests?

2023-02-19 11:31 UTC, srieteja commented
> Unit tests?

Working on them. There's a minor inconvenience, I'm unable to pass a mock object of the PutRequestTransformer into putInternal() trying to figure out.

2023-02-19 11:37 UTC, gkc commented
@srieteja Simple tests: extract the relevant code into its own place and just test that. I've pushed a change with that refactoring.

2023-02-19 11:39 UTC, gkc commented
@srieteja Now you can write unit tests which create AtKeys with various combinations of key and namespace, then call the `ensureLowerCase(AtKey atKey)` method on the AtClientImpl, and then verify the state of the AtKey afterwards

2023-02-19 22:37 UTC, gkc approved these changes
LGTM

2023-02-19 22:37 UTC, merged